source 'https://rubygems.org'
ruby '2.0.0'
gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-r18n', :require => 'sinatra/r18n'
gem 'pdfkit', :require => 'pdfkit'
gem 'wkhtmltopdf-binary'
gem 'nokogiri', :require => 'nokogiri'